#!/usr/bin/env node

const { URL } = require("url");
const md = require("markdown-it")({
  linkify: true,
  html: true
});
const fs = require("fs");
const mjml2html = require("mjml");
const octokit = require("@octokit/rest")();
const ogs = require("open-graph-scraper");
const path = require("path");
const truncate = require("truncate");

function usage() {
  console.error('Usage: \n  script/create-newsletter 19 "8 Feb 2019"');
  process.exit(1);
}

const issue = process.argv[2];
const date = process.argv[3];

// prettier-ignore
const MAILCHIMP_HEADER_IMAGES = {
   2: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/6441b0d8-bf34-4a9a-bed3-657beb2c5c9b.png",
   3: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/7dcbb11f-a1e4-46ef-8c7e-0abfec7bda97.png",
   4: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/1b1bde12-b7ad-46ab-acbb-df5fb7216aaf.png",
   5: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/26c03b91-f776-4149-bbdf-58813cfe9828.png",
   6: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/04ecb2e4-bf1b-4942-91c9-275fa7bffde7.png",
   7: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/891dea1c-21c9-400e-a265-ec93d388fc25.png",
   8: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/bc922b05-2122-4743-8ecb-a6be2a69ca6b.png",
   9: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/10fb86e7-bd1e-4a39-943c-897dc9d98d24.png",
  10: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/87ebf885-d51a-437b-9260-df40fc269052.png",
  11: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/e6e3ea64-d309-4b41-91f8-53042e37dd33.png",
  12: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/c4112e2d-5599-4d16-a684-75d72a01478b.png",
  13: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/7cdda058-a636-4dc4-9135-25341e7714f3.png",
  14: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/3d4c4a76-0f80-4cd6-bcaa-43e343314eb0.png",
  15: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/fec6a8f5-fb74-46f4-95d3-975e72bee4d2.png",
  16: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/059530ec-cd12-4b02-88eb-2775b3bc819c.png",
  17: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/ff35786f-4c77-439c-b6bc-2aec5d6bf00a.png",
  18: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/2c0d5aaa-0ea7-4d93-93ca-7e1196d04827.png",
  19: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/d30817ff-952a-4641-9fba-e91c69c2ab11.png",
  20: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/30bebe0a-56e7-4fc6-b391-f0dc85abb1b5.png",
  21: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/a2843cc8-6db6-4ca8-8270-0c11202f062c.png",
  22: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/e54d9a21-5633-441b-85c1-c59349f83e9b.png",
  23: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/4a076a54-9afc-4942-b03f-e45c40af0020.png",
  24: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/33000e37-8682-4769-8baa-7bf4e94dc9d0.png",
  25: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/250bf2b0-b582-48cd-b976-56fcca12d2db.png",
  26: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/b186c3e1-e48e-409b-9bc9-46a2804dfea3.png",
  27: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/76c9af24-872a-47cd-8842-66236dd73f3e.png",
  28: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/4add0e50-7671-400b-af95-dba29175f532.png",
  29: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/6099d86c-f09f-4dee-92c5-f6bedfb834c1.png",
  30: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/b7a65db6-02e1-4516-a754-e3aadbea5dbb.png",
  31: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/bf0cdcff-9c88-4aa0-bf2d-1f33de87d930.png",
  32: "https://gallery.mailchimp.com/155aa5558694a008de40fe987/images/3dc7248e-0024-43b5-a185-192fc73fdece.png",
};

if (!issue) {
  console.error(`Invalid issue number passed as parameter: ${issue}\n`);
  usage();
}
if (!date) {
  console.error(`Invalid date passed as parameter: ${date}\n`);
  usage();
}

const SRC_DIR = path.join(__dirname, "../src");

const rawFile = fs.readFileSync(`${SRC_DIR}/issues/${issue}/README.md`, {
  encoding: "UTF-8"
});
const tweets = rawFile.split("---").map(s => s.trim());

let cards = [];

let calledTimes = 0;
function done() {
  if (calledTimes < tweets.length - 1) {
    calledTimes++;
    return;
  }

  fs.writeFileSync(`${SRC_DIR}/issues/${issue}/email.html`, createEmail(cards));
  fs.writeFileSync(`${SRC_DIR}/issues/${issue}/index.html`, createIndex(cards));

  console.log("Done.");
  process.exit(0);
}

tweets.forEach(async (tweet, index) => {
  const endsWithUrl = tweet
    .split(/\s+/)
    .slice(-1)[0]
    .startsWith("http");

  if (!endsWithUrl) {
    cards[index] = createCard(index, tweet);
    done();
  } else {
    const url = tweet.split(/\s+/).slice(-1)[0];
    const imageUrl = await urlToImage(url);
    cards[index] = createCard(index, tweet, url, imageUrl);
    done();
  }
});

function simpleMarkdown(text) {
  return md.render(text);
}

const GITHUB_TITLE_SEPARATOR = /(.*)\ ·\ (Pull\ Request|Issue)\ (.*)/;
function createCard(index, tweet, url, imageUrl) {
  let openDataLink = "";
  let text = tweet;

  if (imageUrl) {
    text = stringReplaceLast(tweet, url, "").trim();

    openDataLink = `
      <table border="0" cellpadding="0" cellspacing="0" style="max-width:100%; min-width:100%; margin-top: 10px;" width="100%">
        <tbody>
          <tr>
            <td height="30px" valign="middle" style="line-height:1.3;">
              <a href="${url}">${url}</a>
            </td>
          </tr>
        </tbody>
      </table>
    `.trim();
  }

  return `
    <mj-section ${index !== 0 ? 'padding-top="0"' : ""}>
      <mj-column css-class="small-padding-mobile">
        <mj-text>
          ${simpleMarkdown(text)}
          ${openDataLink ? openDataLink : ""}
        </mj-text>
      </mj-column>
    </mj-section>
  `.trim();
}

function createEmail(cards) {
  const template = fs.readFileSync(`${SRC_DIR}/email-template.mjml`, {
    encoding: "UTF-8"
  });

  const cardsHtml = cards.join("\n");
  let html = template.replace("PASTE HTML HERE", cardsHtml);
  html = html.replace(/Issue 1 \– 21 Aug 2018/g, `Issue ${issue} – ${date}`);
  html = html.replace(
    "./issue.png",
    MAILCHIMP_HEADER_IMAGES.hasOwnProperty(issue)
      ? MAILCHIMP_HEADER_IMAGES[issue]
      : "./issue.png"
  );

  return mjml2html(html).html;
}

function createIndex(cards) {
  const template = fs.readFileSync(`${SRC_DIR}/index-template.mjml`, {
    encoding: "UTF-8"
  });

  const cardsHtml = cards.join("\n");
  let html = template.replace("PASTE HTML HERE", cardsHtml);
  html = html
    .replace(/Issue 1 \– 21 Aug 2018/g, `Issue ${issue} – ${date}`)
    .replace(/\<a /g, '<a target="_top" ');

  return mjml2html(html).html;
}

async function urlToImage(url) {
  let match;

  // We test special URL patterns to extract the proper image e.g for a Github
  // view that shows all commits of a given user.
  const GITHUB_COMMIT_FILTER_URL_REGEX = /\/commits\?author=([a-zA-Z0-9-_]+)/;
  if ((match = url.match(GITHUB_COMMIT_FILTER_URL_REGEX))) {
    const [_, username] = match;
    const result = await octokit.users.getForUser({ username });
  } else {
    return new Promise((resolve, reject) => {
      ogs({ url, timeout: 5000 }, function(error, ogsResults) {
        if (error) {
          reject(new Error("Error:", error, ogsResults));
          return;
        }

        let ogUrl = ogsResults.data.ogImage.url;
        if (ogUrl && ogUrl[0] === "/") {
          const parsedUrl = new URL(url);
          ogUrl = parsedUrl.origin + ogUrl;
        }
        resolve(ogUrl);
      });
    });
  }
}

function stringReplaceLast(string, prevWord, newWord) {
  const n = string.lastIndexOf(prevWord);
  return string.slice(0, n) + string.slice(n).replace(prevWord, newWord);
}
